### ISSUE TITLE
Object axis facing addressee not found

### ISSUE THREAD

**Issue by elizlee** [isi-vista/adam#420]
Currently, `curriculum_to_html.py` crashes as a result of two sets of `GeonAxis`s having no intersection. An error like this is given:
```
Traceback (most recent call last):
  File "/Users/isiboston/Documents/projects/gaila/adam/repos/adam/adam/curriculum_to_html.py", line 919, in <module>
    parameters_only_entry_point(main, usage_message=USAGE_MESSAGE)
  File "/Users/isiboston/miniconda3/envs/adam/lib/python3.6/site-packages/vistautils/parameters_only_entrypoint.py", line 37, in parameters_only_entry_point
    main_method(params)
  File "/Users/isiboston/Documents/projects/gaila/adam/repos/adam/adam/curriculum_to_html.py", line 129, in main
    random_seed=random_seed,
  File "/Users/isiboston/Documents/projects/gaila/adam/repos/adam/adam/curriculum_to_html.py", line 214, in dump_to_html_as_sorted_by_utterance_length
    perception=self._perception_text(perception),
  File "/Users/isiboston/Documents/projects/gaila/adam/repos/adam/adam/curriculum_to_html.py", line 726, in _perception_text
    dfs_walk(root)
  File "/Users/isiboston/Documents/projects/gaila/adam/repos/adam/adam/curriculum_to_html.py", line 722, in dfs_walk
    dfs_walk(succ, depth)
  File "/Users/isiboston/Documents/projects/gaila/adam/repos/adam/adam/curriculum_to_html.py", line 713, in dfs_walk
    relation_str = self._render_relation(axis_info, region_relation)
  File "/Users/isiboston/Documents/projects/gaila/adam/repos/adam/adam/curriculum_to_html.py", line 783, in _render_relation
    f"direction={sign(filler2.direction.positive)}"
  File "/Users/isiboston/Documents/projects/gaila/adam/repos/adam/adam/axes.py", line 171, in to_concrete_axis
    f"Could not find axis of {self._object} facing addressee {addressee}. Axis info is "
RuntimeError: Could not find axis of chair_0 facing addressee person_1. Axis info is AxesInfo(addressee=person_1, axes_facing=i{person_1: {side-to-side[-curved, +directed, -aligned_to_gravity], side-to-side-1[-curved, -directed, -aligned_to_gravity], left-to-right[-curved, -directed, -aligned_to_gravity], left-to-right[-curved, -directed, -aligned_to_gravity]}}).  Axes of object is {front-to-back[-curved, +directed, -aligned_to_gravity], bottom-to-top[-curved, +directed, +aligned_to_gravity], side-to-side[-curved, +directed, -aligned_to_gravity]}
```

**Comment by gabbard** [comment]
@elizlee : Can you make a simple unit test which can recreate the problem?

**Comment by elizlee** [comment]
Additional observation: the only situations that cause the program to crash appear to come from the `behind-in-front` curriculum.

**Comment by gabbard** [comment]
@elizlee : I believe those are the only situations we currently have which depend on axes relative to the speaker or learner.
